### PR TITLE
Chuong/ensure valid move

### PR DESCRIPTION
**Pull request by chuong**
Some highlights of this PR:
- Connect piece drag-drop with valid_move?() and move_to() using jQuery.ajax.
- Add obstruction case when there's a piece of same color at destination.
- Make sure only un-captured pieces are displayed and considered for obstruction.

It looks like the chess app now is quite slow and needs some optimisation.

### CODE REVIEW

**Review by dmk1991 — CHANGES_REQUESTED** [review]
@chuong I just pushed up a commit that just goes through and fixes the knight spec to not throw errors due to some of the new features.  There are still some test errors though within the piece class, specifically with the is_obstructed method. The method seems to be returning the opposite of what is expected in each test.

I'm not entirely sure what is causing this to happen, but we'll need to address this before we can merge this in. I'll keep digging in and see if I can spot whatever quirk is causing this.

**Comment by dmk1991** [comment]
@chuong Well that was actually a lot simpler than expected :P It wasn't a bug in the code, just the factory. The factory for the piece class was not setting captured to false which was causing the other tests to not see any of the pieces since we are now using the new active scope everywhere. I'll push the change up in a second.

**Comment by chuong** [comment]
Thanks @dmk1991, I have been doing the same thing to fix errors. 
Apart from this, please check if you are happy the new features. 
I am going to bed now. See you at meeting tomorrow.

**Comment by dmk1991** [comment]
@chuong The tests are passing now so that's all set. The rest of the changes are sweet! It's pretty cool playing with the board and pieces and seeing how they interact with the code. I only made one change, and that was in the show.html.erb. Instead of using captured: false in the find_by, I switched it to use the active scope just to remain consistent with the rest of your implementation.

One other thing to note, from what I can tell we are no longer using the show method within the pieces controller. If that is true, we should probably remove it since it no longer adds any used functionality. I figured I'd like you make that call though because I may be mistaken.

Super awesome work man! Other than possibly removing the pieces#show action, I think this is good for a merge.

**Review by dmk1991 — APPROVED** [review]

**Pull request merged**
