### PR TITLE
Implement castling

### PR DESCRIPTION
**Pull request by dmk1991**
# Castling
PR to implement the ability to castle. The implementation took two steps, creating a method to confirm that castling was valid (can_castle?) and overriding the parent implementation of move_to.

- can_castle? confirms that neither the king or rook have moved, that a rook is present at the specified corner, and confirms that there are no obstructions between king and rook. Technically, this implementation would allow for a castle to happen if a rook is not on it's corner, but also has never moved. Since this is impossible an actual game, this didn't seem to be a big deal.

- In order to facilitate the actual move I overrode the parent move_to method. The method checks again if castling is valid, and if it is, moves the pieces accordingly.  If castling is not valid, the method simply calls super and relies on the logic of the parent method to handle the move.

Let me know what you think.

### CODE REVIEW

**Comment by dmk1991** [comment]
I'll rebase this tonight to deal with the conflicts.

**Comment by dmk1991** [comment]
Branch has been rebased on top of the new master. Please review when you get a chance.

**Review by chuong — APPROVED** [review]
@dmk1991 Great work with king castling. Later we can add more specific cases when the king is in check at current or new position and any square in between.

**Comment by dmk1991** [comment]
@chuong Thanks for the review! Once we see how Ryan handles preventing people from moving into check we'll have to just double check to make sure it works with this special use case as well.

**Pull request merged**
