### PR TITLE
Chuong/drag drop pieces

### PR DESCRIPTION
**Pull request by chuong**
Implement drag and drop pieces using jquery-ui.
- Make pieces to appear on layer above that of squares, and change cursor shape when hovering over pieces
- Make pieces draggable.
- Make squares to accept drop action and perform a simple capture action if another piece already is inside.
For now, no check for valid move or valid capture.

### CODE REVIEW

**Review by dmk1991 — CHANGES_REQUESTED** [review]
@chuong Something I noticed while playing with the drag and drop functionality. If you pick up a piece and place it back down on it's same square, the piece just fades away. I think this may possibly have to do with the capture if statement, but I'm not positive.

**Comment by chuong** [comment]
@dmk1991 Well spotted David. I am fixing this with a new commit.

**Comment by chuong** [comment]
@dmk1991 These commits should fix the error. Please check again. Thanks.

**Comment by chuong** [comment]
@dmk1991 These should fix the error. Please check again. 

Your PR#26 looks promising and I am happy to rebase my PR on it. Currently I cannot check out `dmk1991:responsive-board` branch because the name has illegal character ":", so I cannot test it. Maybe you have to merge it into master branch. From there, I will start rebasing my work on it. Another way around is to merge my PR first and rebase your PR#26 on top. Either way, I expect several conflicts.

**Comment by dmk1991** [comment]
Taking a look now!

**Review by dmk1991 — APPROVED** [review]

**Comment by dmk1991** [comment]
Looks good to merge @chuong.

**Pull request merged**
