### PR TITLE
This is the database structure that myself and Chuong came up with.

### PR DESCRIPTION
**Pull request by ryank01**
Here is a link to database schema 
https://docs.google.com/spreadsheets/d/1HPbFs3qmYpgr2tVsWoFD4Yr4X25zUBS8lFPwku8Xjzo/edit#gid=770253114
Look at sheet 2 
Please have a look and verify.

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
@ryank01 and @chuong:

This looks good!  One bit of feedback: the app is going to need to display the current board a lot.  Like the user will want to see the board, when a piece is about to move, it will need to check to make sure there's not a piece blocking the move, etc.  With the schema above, you can calculate the positions of all the pieces given the list of moves taken so far, but that would be kinda complex if you had to do it every time you needed to access the board.

My suggestion would be to create a Piece model and backing database table, probably like:

* type:string
* row:integer
* column:integer

`type` is actually a special field name - Rails has something called Single Table Inheritance, which means you can do the class inheritance you've already started, and Rails will store the name of the class inside that `type` column.  You don't have to do anything special other than add the type column in the migration and then subclass your sub-models:

```ruby
class Piece < ActiveRecord::Base
end

class Rook < Piece
end

class Pawn < Piece
end

# ...
```

Rails takes care of the rest.

**Comment by ryank01** [comment]
Ok thanks for the feedback will look into this.
Thanks

**Comment by chuong** [comment]
Thanks Jacob. It makes good sense to add a Piece class/table. That means Pieces table stores the update-to-date layout of the chessboard with all the pieces?

Once this done, how do we link Piece class to other class such as Game and Move? Or it can stand alone?

**Comment by jacobwgillespie** [comment]
Sounds good - probably the Piece would `belongs_to :game`.  It probably also needs a field for storing the color (white / black).

**Comment by chuong** [comment]
@ryank01 Shall we close this PR #3, without merging it, as PR #5 is more up-to-date?

**Pull request closed without merging**
