### PR TITLE
Adds classes for STI.

### PR DESCRIPTION
**Pull request by dmk1991**
# Implement Single Table Inheritance on the Piece table.  

- Created all new models using rails generate with --no-migration and --parent=piece options.
- Generator created appropriate factories and specs for models.  Removed previews from specs.
- Model now exists for each piece type, all extending the piece class.

Please review and let me know if were good to merge.
Thanks!

### CODE REVIEW

**Comment by iandelible** [comment]
Is there a reason for not making a pawn_spec.rb?

**Comment by dmk1991** [comment]
No reason in particular. I manually created the pawn class before I realized rails has flags you can use to get the controller generator to support STI. Good catch, I'll add it when I get home and push up the changes.

**Comment by dmk1991** [comment]
Pawn_spec added to PR. When someone gets a chance, can we get a second confirmation from someone before the merge?

**Comment by iandelible** [comment]
factories.rb also missing the pawn factory. we might as well add it for consistency?

**Comment by dmk1991** [comment]
Removed the unnecessary factories since all "pawns", "rook", etc... are all extensions of the piece class so whenever creating one as a test you will just create a piece with a type that you need.

**Comment by dmk1991** [comment]
I think this is good to merge at this point.  I double checked in the rails console to make sure the sub classes were extending piece and they are. Can I get one more checkout / thumbs up from someone before the merge to confirm I'm not missing something obvious? Thanks!

**Comment by dmk1991** [comment]
Fixed the merge conflict, since no one else has had any comments I'm gonna go ahead and merge this into master.

**Pull request merged**
