### PR TITLE
Fix game controller typo

### PR DESCRIPTION
**Pull request by dmk1991**
# Typo fix in Games controller
There was an extra & on line 51 in the game controller.  This was throwing an application error once pushed to Heroku. I've removed the & in this PR, so once we get this merged in I think Heroku should be working.

### CODE REVIEW

**Comment by chuong** [comment]
@dmk1991 that & is a short hand Ruby operator to test if the last move exists before checking if it is a black piece. Otherwise it will crash when there's no move to undo. Not sure why this operator caused error on Heroku.

**Comment by dmk1991** [comment]
@chuong Oh, wow. I wasn't aware of that shorthand. Completely disregard this "fix" then. I'm not sure what Heroku is complaining about then but it was specifically pointing to that line and that file and the & i removed was the only obvious syntax error.

**Comment by dmk1991** [comment]
Oh, I think I see what the problem may be. According to this article, http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/, the operator you are using was introduced in Ruby 2.3. Currently Heroku is using 2.2 so it has no idea what you are trying to say. We likely just need to tell our production environment to use 2.3 instead and all should work out.

**Comment by dmk1991** [comment]
Hmm, our Travis CI config is telling it to use 2.3.1 so I'm not entirely sure the logs seem to indicate that 2.2 is in use. @jacobwgillespie Any thoughts about this? Relevant snippet of log lines is in Slack.

**Comment by chuong** [comment]
We can specify Ruby version by adding a line in Gemfile such as `ruby "~> 2.3.0"`, as mentioned at https://devcenter.heroku.com/articles/ruby-versions

**Comment by chuong** [comment]
@dmk1991 Could you please apply the fix for Ruby version and merge as soon as possible to fix error on Heroku? Thanks.

**Comment by dmk1991** [comment]
Getting it pushed up now in a new branch / PR. Closing this one due to the errors.

**Pull request closed without merging**
