### PR TITLE
database revision

### PR DESCRIPTION
**Pull request by chuong**
This pull request is update of pull request #3 by @ryank01, following comments from @jacobwgillespie.
Updated schema is on sheet "Ver 0.2" of  https://docs.google.com/spreadsheets/d/1HPbFs3qmYpgr2tVsWoFD4Yr4X25zUBS8lFPwku8Xjzo/edit?usp=sharing

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Nice, this looks good to me!  🎉 

@ryank01, you have any further comments or is this ready to merge?

**Comment by dmk1991** [comment]
Awesome job guys! The question I have is about Games and Players.  Both have a statement like "has_many :players, or has_many :player_games".  Has a decision been made on which way you want to move forward with?

**Comment by chuong** [comment]
@dmk1991 It looks like you looked at the old database schema on sheet Ver 0.1, instead of the newer schema on sheet Ver 0.2 of the above Google spreadsheet. In fact this pull request includes your " Build the models and migrations for initial database design" task. Sorry for that, @ryank01 and I implemented this because it's difficult to validate the database schema without implementing the models.

**Comment by dmk1991** [comment]
Ah! That makes sense.  I must have reopened it and not switched without realizing.  Disregard my comment then :P And no worries about implementing the models and migrations.  I understand how having actual data to work with can make things much easier. Seems good to go for a merge to me. 👍

**Comment by chuong** [comment]
Something comes up I have to cancel my meeting today. Chuong

**Pull request merged**
