### PR TITLE
Chuong/rooms

### PR DESCRIPTION
**Pull request by chuong**
Add view games, join/leave button as black player, top navbar.

### CODE REVIEW

**Comment by chuong** [comment]
I got tests failed due to addition of "before_action :authenticate_player!" in GamesController. Tried to resolve this but errors keep coming back. Any idea?

**Comment by jacobwgillespie** [comment]
Looks like the test helpers for devise aren't being enabled - you'll want to add the following to the top of the `rails_helper.rb` file:

```ruby
include Warden::Test::Helpers
```

**Comment by chuong** [comment]
@jacobwgillespie If I add that line, I got these errors 
`$ bundle exec rspec
/vagrant/src/chess-app/spec/rails_helper.rb:1:in `<top (required)>': uninitialized constant Warden (NameError)
	from /vagrant/src/chess-app/spec/controllers/games_controller_spec.rb:1:in `require'
	from /vagrant/src/chess-app/spec/controllers/games_controller_spec.rb:1:in `<top (required)>'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /home/vagrant/.rbenv/versions/2.3.0/bin/rspec:23:in `load'
	from /home/vagrant/.rbenv/versions/2.3.0/bin/rspec:23:in `<main>'
`

**Comment by chuong** [comment]
I think the situation was that the Player model was created before Rspec was setup so there are some files missing for Player model.

**Comment by chuong** [comment]
I tried adding `players_helper.rb`, `players_spec.rb` and update

`games_controller_spec.rb` to 
```
require 'rails_helper'

RSpec.describe GamesController, type: :controller do
  describe 'games#show' do
    it 'should render game board for existing game' do
      game = FactoryGirl.create(:game)
      player = FactoryGirl.create(:player)
      sign_in player

      get :show, id: game.id
      expect(response).to have_http_status(:success)
    end

    it 'should render 404 if game does not exist' do
      get :show, id: 141231234309284
      expect(response).to have_http_status(:not_found)
    end
  end
end

```
 `factories.rb` to
```
FactoryGirl.define do
  factory :piece do

  end

  factory :move do

  end

  factory :game do
    name 'test'
    white_player_id 1
    black_player_id 2
  end

  factory :player do
    sequence :email do |n|
      "dummyEmail#{n}@gmail.com"
    end
    password "secretPassword"
    password_confirmation "secretPassword"
  end
end
```
I still got these test failures
```
$ bundle exec rspec
FF

Failures:

  1) GamesController games#show should render game board for existing game
     Failure/Error: sign_in player
     
     NoMethodError:
       undefined method `sign_in' for #<RSpec::ExampleGroups::GamesController::GamesShow:0x007f97eac8cee8>
     # ./spec/controllers/games_controller_spec.rb:8:in `block (3 levels) in <top (required)>'

  2) GamesController games#show should render 404 if game does not exist
     Failure/Error: get :show, id: 141231234309284
     
     Devise::MissingWarden:
       Devise could not find the `Warden::Proxy` instance on your request environment.
       Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
       If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.
     # ./spec/controllers/games_controller_spec.rb:15:in `block (3 levels) in <top (required)>'

Finished in 0.09995 seconds (files took 2.82 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/controllers/games_controller_spec.rb:5 # GamesController games#show should render game board for existing game
rspec ./spec/controllers/games_controller_spec.rb:14 # GamesController games#show should render 404 if game does not exist

```

**Comment by dmk1991** [comment]
Chuong, you were just missing adding the devise helpers in the rails_helper config. Pushed up the change and added in your changes to the controller spec.

**Comment by dmk1991** [comment]
My only other comment for this PR is that all of those helpers should be placed in the private scope.  When they're outside of the private scope rails might think they are controller actions, or at least that's my understanding of how rails looks at controllers.

**Comment by dmk1991** [comment]
No problem Chuong!

**Comment by chuong** [comment]
@dmk1991 Again thanks for your wonderful help. I moved the game helpers to private scope as you suggested. Are you happy for this to merge?

**Comment by dmk1991** [comment]
@chuong In regards to my previous comment about the helpers, you will need to move the actual function declarations down into the private scope as well. This would be lines 16 - 34 in the "games_controller.rb" file. Other than that I think you are good to go with a merge! Thanks for the hard work Chuong!

**Comment by chuong** [comment]
@dmk1991 Thanks David for sharp eyes. I made the change and merge now

**Comment by dmk1991** [comment]
Great, good work @chuong!

**Pull request merged**
