### PR TITLE
Chuong/keep track of turns

### PR DESCRIPTION
**Pull request by chuong**
Changes to keep track of player turns and update chessboard with move by remote player:
- Add Pusher gem for remote notification and Figaro to load environment variables.
- Add active player field to Game to keep track of turn.

Please have a look and test it out. I share my `config/application.yml` file for Pusher's settings in our slack channel. You need to log in chess-app from two different user accounts on different browsers or machines to test player turn effect.

### CODE REVIEW

**Comment by chuong** [comment]
This PR may need a unit test for turn checking. Haven't figured out how to do this as it currently ties to front end.

**Comment by dmk1991** [comment]
@chuong In regards to the unit tests, you would probably want to test the controller actions. You could sign in as a user, create a game, and then make a post request to make a move. You can then make an assertion that the active player is now black and not white. You could take a look at my test code for pawn promotion to get an idea of how I was able to confirm that the controller would properly handle requests once I get the front end working.

**Comment by dmk1991** [comment]
@chuong Just pulled down the PR and took a look. Awesome job! I'm over here playing chess with myself just to watch the update happen haha. I think this is good for a merge once the conflicts have been resolved. I think most of the issues is that I added a bit of javascript to show.html.erb as well in order to handle pawn promotion. My update action also has a few changes that got merged into master as well.

I'll need to keep the JavaScript stuff, but you can get rid of the update action things that I did. Going to take a different route once I have checkmate done.

**Comment by chuong** [comment]
@dmk1991 I fixed new errors, and add tests for tracking turns and player color move. Please have a look. Thanks.

**Comment by chuong** [comment]
Not sure what you meant "get rid of the update action that I did". It seems the stuff works for now. I merge this now so I can rebase my other PR onto master.

**Pull request merged**
