### PR TITLE
Chuong/castling frontend

### PR DESCRIPTION
**Pull request by chuong**
- Deal with normal move and castling move and refresh remote front end
- Add reset game button to reset board, useful for testing front end.

Suggest to add "undo last move" feature.

### CODE REVIEW

**Comment by dmk1991** [comment]
@chuong Again, awesome work with the front end Chuong. The integration seems to be working perfectly. I tested out castling in both directions and with both colors. Some of the pusher stuff is outside my understanding (I've never used it before), but it seems to be doing the job correctly.  

One question though, do we want to have the reset button merged into the actual game or was that just for testing? I'm not sure that is a feature we'd want to have since anyone could just press it whenever they are losing :stuck_out_tongue:

**Comment by chuong** [comment]
This is useful during development, especially to test special case. For frontend, it's a hassle to create a new game every time you want to repeat a test. In fact, an undo button would be better but it will take more time for me to implement. I would tend to leave the function in there and disable it when we complete the development.

**Comment by dmk1991** [comment]
Makes complete sense. We'll just have to make sure that we remember to delete it before we go live :P

**Comment by chuong** [comment]
@dmk1991 This should work as expected now. I will try to replace Reset Game button by an Undo Last Move button.

**Comment by chuong** [comment]
@dmk1991 Now the "reset game"  button has been replaced by an "undo last move" button . A player can undo only the last move was made by this player and the last move is removed from the move list. Therefore a player can only undo several move when the opponent undoes his/her moves in turn. This undo button currently work with normal move, move with capture and king castling. You need to login in with 2 accounts from 2 different browsers to test this feature.

**Comment by dmk1991** [comment]
@chuong Awesome! I'll pull it down tonight and take a look.

**Comment by dmk1991** [comment]
Looks good for a merge. Only comment I have is that there is no feedback to the end user if they press the button and they can't undo a move because the last move isn't their turn. This could be confusing when trying to use the button. Code looks good to merge though if you'd like to get this into master and we can add some sort of notification as time allows.

**Comment by chuong** [comment]
@dmk1991 Thanks for you feedback. I am gonna merge this into master and will add notification soon.

**Pull request merged**
