### PR TITLE
Added rspec and Factorygirl

### PR DESCRIPTION
**Pull request by ryank01**
Rspec and Factory girl

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
LGTM 🎉

**Comment by jacobwgillespie** [comment]
@ryank01 you are free to merge your PR as soon as it has approval from a reviewer (like above) 👍

**Comment by ryank01** [comment]
Ok thanks will merge this ASAP!
Thanks Jacob ..

**Comment by chuong** [comment]
@ryank01 I just resolved the conflicts and merged so that the next pull request #4 can follow.

**Comment by chuong** [comment]
@ryank01 In fact this merge to make way for @jacobwgillespie to add Heroku repository.

**Pull request merged**
