### PR TITLE
Chuong/pieces on board

### PR DESCRIPTION
**Pull request by chuong**
Collection commits for displaying pieces on chessboard.

### CODE REVIEW

**Comment by dmk1991** [comment]
@chuong I am out of the house right now, but when I get home I'll take a look real quick.

**Comment by dmk1991** [comment]
Nice work Chuong, just a couple things to note from me.

* The CSS in the show page should probably get moved to it's own css file, or a master css file. (I can do this if you'd like since I don't have much else to do this week other than help people).
* You may be able to move the symbol hashes you have into a helper function that returns back the appropriate symbol instead of passing an entire hash into the view. I can be available tonight to discuss this further if you'd like to look into it.

**Comment by chuong** [comment]
@dmk1991 Thanks for the comments. I tried to move the CSS to game.css or master.scss but it caused some changes to the board so I keep them in current position for now. If you are interested in fixing this within this PR, please do so. The same for symbol hash. I think this is a good way to write codes together.
Currently I focus on getting the mouse click detection to move the pieces.

**Comment by dmk1991** [comment]
Ok, sounds good Chuong. I'll look into it.

**Comment by dmk1991** [comment]
Commit I just pushed up moves the CSS into it's own file and changes some of the hard set values into a Bootstrap classes so that we can eventually switch into a responsive design instead of hard set values. I don't want to break any of your good work so I think doing a merge now would make sense. I'll open a new branch and PR at some point to try and get the board a little more responsive to other screen sizes.
👍

**Comment by dmk1991** [comment]
Ended up having some extra time on my hands than I thought I did.  Just did the transition over to helper methods to select what color a square is and what symbol should go on that square if a piece exists on the row / column coordinate.

**Comment by chuong** [comment]
@dmk1991 Great work David! I merge this PR now.

**Pull request merged**
