### PR TITLE
Implement populate game method

### PR DESCRIPTION
**Pull request by dmk1991**
# Implement populate_game! method
Hey everyone, finished up an initial populate_game! method and wanted to get it up here and merged in asap so that everyone else who needs the pieces to complete there work this week can use it. I'll be looking for ways to reduce the amount of repetitiveness in the near future, but wanted to first make sure everyone had a working method.

### Notable Changes
* Adds new method into Game model
* Adds tests into game_spec to double check that all of the counts are correct.

Please let me know of any comments / questions / concerns. Hopefully we can get this merged into master early tomorrow. If you need the method before then, it should be easy enough to pull in my changes to your current feature branch.

### CODE REVIEW

**Comment by chuong** [comment]
@dmk1991 Nice work. I cannot test myself (somehow I cannot checkout dmk1991:implement-populate-game-method branch) but all travis-ci tests passed and the codes look good. So please merge this PR as soon as possible.

**Comment by chuong** [comment]
Sorry David. I cannot wait for you so I am merging this PR now as I need to work on it. Great work!

**Comment by dmk1991** [comment]
Sorry Chuong, my phones WiFi was of so I never saw the notice. Thanks for doing the merge. 

One thing to note, the method populates the pieces with an assumption that the first row and first column are 1, not 0.

**Comment by dmk1991** [comment]
Oh! And you will need to run db:migrate as well once you pull in the new master branch. Needed to modify the type field to a string so that STI works properly

**Comment by chuong** [comment]
@dmk1991 yes, I did a rake db:migrate. It was my mistake to set type field to integer initially.

**Pull request merged**
