### PR TITLE
Responsive board

### PR DESCRIPTION
**Pull request by dmk1991**
# Modified board to a more responsive design.
Hey everyone, I took some time and modified the show.html.erb page which was used to render the chessboard and utilized boostrap and media queries to allow it to responsively re-size itself on different browser sizes. Since this may affect @chuong I wanted to get it up asap to see if anyone was interested in making this switch. We don't need to do this merge, but I felt it might be nice to start accounting for how the page will actually look live.

- Changed classes to utilize Bootstrap grid
- Moved square rendering into helper methods
- Switched from pure divs into a html table

Let me know what you think.

### CODE REVIEW

**Comment by chuong** [comment]
@dmk1991 This PR looks promising and is something I would like to see how the page should be. I would like it to be merged as soon as possible, although I wish you did this after PR#23 being merged so we don't have to spend extra time to fix conflicts. I cannot check out your PR and test it but I believe in your code quality. 

It would be helpful to avoid ":" character in your branch name as in `dmk1991:responsive-board` because the branch does not show up in repository branch list and and I cannot checkout it to test (got  `error: pathspec 'dmk1991:responsive-board' did not match any file(s) known to git`).

**Comment by dmk1991** [comment]
@chuong I'm fine with either merging now, or just doing a rebase after PR#23 gets merged in and I can clean up the issues that it causes.  This is more a quality of life improvement and shouldn't take priority over your other work.

In regards to the branch, the name is only responsive-board but is hosted on my forked repository (i.e. dmk1991:responsive-board). If you look next to the "Merge pull request" button you'll see command line instructions to grab the branch.  Just don't follow step 2 since that will actually do the merge, where as step one only pulls down the local branch for your viewing.

```
git checkout -b dmk1991-responsive-board master
git pull https://github.com/dmk1991/chess-app.git responsive-board
```

**Comment by chuong** [comment]
@dmk1991 Could you please rebase this PR as soon as possible? I would like it to be merged before I work on my next task. Great work!

Thanks for the explanation. Sorry that I didn't recognise this PR from a different repository.

**Comment by dmk1991** [comment]
@chuong I'll work on it tonight when I get home from work :)

**Comment by dmk1991** [comment]
@chuong Ok, I merged in your changes and just change the selectors within your JavaScript to interact with the appropriate css classes.

**Comment by dmk1991** [comment]
@chuong Hey man, I'm gonna be heading to bed shortly. If you like the changes, feel free to do the merge so that you can start working on the rest of the features.

**Comment by chuong** [comment]
@dmk1991 Great work with the resizable chessboard! Some minor issues with the aspect ratio of the squares and the missing chessboard border. However these can be addressed later. I'm gonna merge this PR now.

**Comment by chuong** [comment]
I put a snapshot of chessboard layout right before this PR as for record when we want to refer this old layout:
chessboard-fixed

**Comment by dmk1991** [comment]
@chuong Yeah, there were a few CSS things that changed the general look of the board, like the border you mentioned. Since these didn't really affect functionality though I figured we could get those resolved when free time arises.

**Pull request merged**
